# Java Gradle CircleCI 2.0 configuration file
# See: https://circleci.com/docs/2.0/language-java/
version: 2.1

orbs:
  codecov: codecov/codecov@3.2.4
  node: circleci/node@4.7.0
  workflows:
    upload-to-codecov:
      jobs:
        - checkout
        - codecov/upload

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      # Only java version 8 or above
      - image: cimg/openjdk:19.0.2

    steps:
      - checkout
      - run: java --version
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
            
            
      # Execution of the unit tests with Maven
      - run:
          name: Run unit tests
          command: |
            mvn clean test

      - run:
        name: Build docs
        command: javadoc -d .\docs\javadocs .\src\main\java\fr\univavignon\pokedex\api\*.java
      - persist_to_workspace:
          root: docs
          paths: javadocs

# Workflows
workflows:
  version: 2.1
  build:
    jobs:
      - build:
        # Execute only on the branch 'master'
        filters:
          branches:
            only:
              -  master