name: Workflow for Codecov example-c
on: [push, pull_request]
jobs:
  run:
    runs-on: windows-latest
    steps:
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
